### ISSUE TITLE
/block endpoint missing transactions

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#115]
This [transaction](https://filfox.info/en/message/bafy2bzaceaxmmk7b56ho4nhtvakshxw3nyytcksgow7l5thdapr4owghkbeoc) is missing when I hit /block endpoint. Ideas? We found it out during our testing. 

```
curl --location --request POST 'http://10.200.201.200:8080/block' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "mainnet"
    },
    "block_identifier": {
        "index": 150558
    }
}'
```

**Comment by raynaudoe** [comment]
That's because the `Exec` method is not listed as a "supported operation" inside the proxy. Also, seems that the trace of that transaction doesn't contain an underlying `Send` tx... so seems that `Exec` falls into the category of what we call "primitive operations" which can produce a balance change. 
AFAIK we were not informed of such effect on the balance for `Exec` methods. Nevertheless, I'll add it on the next proxy update.

If someone from Lotus could help us clarify this will be very appreciated !

**Comment by arajasek** [comment]
@raynaudoe I don't think I understand what you mean. Idk what is considered as a "supported operation" and what isn't, but there should definitely be a `Send` subcall in the trace when the init actor (`f01`) calls the Constructor of the appropriate actor.

```
Replay receipt:
Exit code: 0
Return: 824400a2b6025502cd96569048279e5f205297f6abbda07e46b00750
Gas Used: 6401417
Total Message Cost: 1211980242751
f1irp52rbfzswlbygw3dr6dhfohc744o4gm6pdtsy       f01     9990000000000000        2       82d82a53000155000e66696c2f322f6d756c7469736967581b8481550105b5a36fc877e9f66bc21b77f45a49b5812a01d7010000        0       824400a2b6025502cd96569048279e5f205297f6abbda07e46b00750
        f01     f039714 9990000000000000        1       8481550105b5a36fc877e9f66bc21b77f45a49b5812a01d7010000  0
```

**Comment by qiwu7** [comment]
@raynaudoe can you add parsing for the Exec method? Looks like this doable.

**Comment by jleni** [comment]
Yep, no problem. I guess that at this stage it makes sense that we write a very quick markdown document describing how we use traces and what operations we consider.
Maybe @arajasek can later review that quickly.

**Comment by raynaudoe** [comment]
> but there should definitely be a Send subcall in the trace when the init actor (f01) calls the Constructor of the appropriate actor.

I'm not being able to find the `Send` transaction by using state-compute:
`lotus state compute-state --vm-height 150558 --show-trace`

And on the proxy side I see the `Exec` transaction but no `Send` on any of the subcalls.

@arajasek did you use `state-compute` or `replay` to get that output ?
