### ISSUE TITLE
Hardcoded network name

### ISSUE THREAD

**Issue by rllola** [Zondax/rosetta-filecoin-proxy#129]
The `NetworkName` value is hardcoded and required to be changed for example run against localnet.

https://github.com/Zondax/rosetta-filecoin-proxy/blob/40df4bab6de053b504a20e7ac9edc7e22b8cb27e/rosetta/services/constants.go#L19

**Comment by raynaudoe** [comment]
That value should be fixed, maybe we can inject that variable at build time, and choose in the makefile if we want a mainnet or a testnet build

**Comment by jleni** [comment]
Can we close this one here?
