### ISSUE TITLE
Rosetta-Filecoin-Proxy Support for Lotus v16 -rc1

### ISSUE THREAD

**Issue by ghost** [Zondax/rosetta-filecoin-proxy#157]
i checked for new node software releases [here](https://github.com/filecoin-project/lotus/releases.): I saw that v1.16.0-rc1 was required for the pre-upgrade to support Filecoin network v16. do you know if rosetta-filecoin-proxy version v1.1600.0-rc1  is compatible with v1.16.0-rc1 Lotus for calibration net

im seeing some errors after upgrading since yesterday my nodes been down
`2022-06-17T00:04:56.491Z	INFO	rosetta-filecoin-proxy	services/errors.go:367	Error on file: account.go:50`
`2022-06-17T00:05:26.405Z	ERROR	rosetta-filecoin-proxy	services/errors.go:369	Proxy: node is not yet fully sync`

upgrade to -> https://github.com/Zondax/rosetta-filecoin-proxy/commit/9d7b95c7c43b745129b2d25b5faf72d27dd2d372

:link: [zboto Link](https://app.clickup.com/t/2mdazh7)

**Comment by raynaudoe** [comment]
Hi @rahsaanpage-coinbase , that release is not yet fully compatible with the lotus release `v1.16.0-rc1` . We're working on getting `rosetta-filecoin-proxy` and `rosetta-filecoin-lib ` updated. 
I've already marked that release as a draft (not production ready), sorry for the confusion!

**Comment by rpage-coinbase** [comment]
hi @raynaudoe what should i do from here to recover?

**Comment by rpage-coinbase** [comment]
Thank you @raynaudoe!!
