### ISSUE TITLE
Extract + inject build time information

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-proxy#21]
Extend Makefile and inject build time information (git revision + mod version for rosetta)

https://github.com/Zondax/rosetta-filecoin-proxy/blob/c84a60d3d6ecc381dcca186b5221856d0e60471a/Makefile#L2

This will improve

References:
https://stackoverflow.com/a/59244274/157726

https://www.yellowduck.be/posts/injecting-build-time-variables/
https://blog.alexellis.io/inject-build-time-vars-golang/

**Comment by raynaudoe** [comment]
Added on #26
