### ISSUE TITLE
construction/metadata

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#28]
I recently found out that `construction/metadata` returns different nonces for an address from 2 different nodes. Both of our nodes are at the tip and one is returning nonce as `10` and the other one is returning nonce as `11` for this address `t1zdqprv6ryul3md3xiqpsczpui7xmqwjztvhirsy` we have been using to test.

Ideas?

**Comment by jleni** [comment]
You said you have a load balancer.

Is there a chance that you sent a tx to one that is still in the mempool of node A but node B is still unware of it?

I would expect that querying account nonces that have pending unconfirmed txs may vary if you query different nodes
