### ISSUE TITLE
Null tipsets on Filecoin's chain

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/rosetta-filecoin-proxy#29]
Seems that there are _several_ empty (or null) tipsets like [this one](https://filfox.info/en/tipset/1249).
This breaks rosetta's consistency check since tipset `1249` doesn't exists and tipset `1250` has `1248` as parent.

Adding a workaround from proxy side could be quite a mess.

**Comment by raynaudoe** [comment]
Using `rosetta-cli` v0.4.1, I confirm that by adding on `block.go`:
```
	if int64(retrievedTipSet.Height()) != requestedHeight {
		return &types.BlockResponse{}, nil
	}
```
This is, when Lotus returns a TipSet at a different height than the requested one, return an empty response with `nil` error. On this case, blockchain consistency is kept thus null tipset won't be a problem for rosetta-cli.

**Comment by jleni** [comment]
Good news
