### ISSUE TITLE
Data API - /account/balance

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#3]
**what** `/account/balance` needs to include the following information
- unlocked balance
- total balance (including both unlocked balance and locked balance)
- vesting schedule
- account nonce

**why** this is essential for our Custody team to be able to show the client their account details.

Note: we will followup with where exactly we want to place these information. But we will be leveraging SubAccounts to expose these information in the API

References: `MsigGetAvailableBalance` returns the unlocked balance of a `Msig`, the actual “balance” of the Msig actor is the total balance (including locked). There isn’t an endpoint to get the actual vesting schedule, but `StateReadState` will get you the StartEpoch and UnlockDuration (it’s always linear vesting).

**Comment by qiwu7** [comment]
request 
```curl --location --request POST '{{NODE_URL}}/account/balance' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnet"
    },
     "account_identifier": {
        "address": "t0128015",
        "sub_account": {
            "address": "LockedBalance",
            "metadata": {}
        },
        "metadata": {}
    }
}'
```

response
```
{
    "code": 42,
    "message": "unable to get locked balance for address",
    "retriable": true
}
```

**Comment by raynaudoe** [comment]
@qiwu7, Filecoin team have recently provided me with better way to get the state of a multisig account.
I'm adding that fix on the next PR.
