### ISSUE TITLE
construction/metadata response keys

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#34]
Currently `construction/metadata` is returning responses with the field keys in [Pascal Case.](https://github.com/Zondax/rosetta-filecoin-proxy/blob/master/rosetta/services/construction.go#L15-L38)
```
// ChainIDKey is the name of the key in the Options map inside a
// ConstructionMetadataRequest that specifies the current chain id
const ChainIDKey = "ChainID"

// OptionsIDKey is the name of the key in the Options map inside a
// ConstructionMetadataRequest that specifies the account ID
const OptionsIDKey = "Id"

// OptionsBlockInclKey is the name of the key in the Metadata map inside a
// ConstructionMetadataResponse determines on how many epochs message should included
// being 0 the fastest (and the most gas expensive one)
const OptionsBlockInclKey = "BlockIncl"

// NonceKey is the name of the key in the Metadata map inside a
// ConstructionMetadataResponse that specifies the next valid nonce.
const NonceKey = "Nonce"

// GasPriceKey is the name of the key in the Metadata map inside a
// ConstructionMetadataResponse that specifies tx's gas price
const GasPriceKey = "GasPrice"

// GasLimitKey is the name of the key in the Metadata map inside a
// ConstructionMetadataResponse that specifies tx's gas limit
const GasLimitKey = "GasLimit"
```

However, the filecoin-lib is taking params in [Camel Case](https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_api.go#L64-L69). Can we unify them so that they are consistent. I am leaning towards snake case. Or we can use camel case if that's preferred. But we want to have them to be consistent

**Comment by jleni** [comment]
Should we stick to Google's JSON style? I think this is fairly standard and easy to reference.

https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format

That is `camelCase`?

**Comment by qiwu7** [comment]
Yeah that works. we are using snake case internally. But camelCase also works!
