### ISSUE TITLE
Sync status tracking

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/rosetta-filecoin-proxy#5]
In order to put some information into rosetta about node's sync status, we temporarily (as workaround) added to the `/network/status` response, specifically into `current_block_identifier.index`, the height of the latest synced block.

Expect also in this case:
 `current_block_identifier.hash`  =  `0000000000000000000000000000000000000000`
  `current_block_timestamp` = `0`

Example response when node is syncing:
```
{"current_block_identifier":{"index":6838,"hash":"0000000000000000000000000000000000000000"},"current_block_timestamp":0,"genesis_block_identifier":{"index":0,"hash":"0171a0e402201c1fb0c2e62d1857e523ea79898051c91e4b042c2ed96c4995c5002789570a210000000000000000"},"peers":[{"peer_id":"12D3KooWHCtoCvWMFodJQsZWCtA1XqxQvtumLWqe1FGwU7PyhVD7"},,...
```

**Comment by raynaudoe** [comment]
Hi @qiwu7 

>     * 1. Use the new `syncing info` field in the API interface to report the status of the message sync process (while keeping current_block_identifer.index == genesis_block_identifer.index == 0)

This new field `syncing info` is already available on the rosetta-sdk ?

**Comment by qiwu7** [comment]
Yes. it's available now with the new release. See PR [here](https://github.com/coinbase/rosetta-specifications/pull/31/files)  ,and the new field in SDK [here](https://github.com/coinbase/rosetta-sdk-go/blob/master/types/network_status_response.go#L35)

**Comment by raynaudoe** [comment]
Great! the release has not been made yet, right?

**Comment by qiwu7** [comment]
It's available with release 1.4.1
https://www.rosetta-api.org/docs/NetworkApi.html#response-2

**Comment by raynaudoe** [comment]
ok! I'll make the update.

**Comment by raynaudoe** [comment]
`SyncStatus` added on  #13
