### ISSUE TITLE
Gas fees estimates

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/rosetta-filecoin-proxy#50]
Lotus provides endpoints for getting:

- **GasEstimateGasLimit**: requires sender address
- **GasEstimateGasPremium**: apparently doesn't need sender's address (asked filecoin about this)
- **GasEstimateFeeCap**: requires setting gasPremium first

This issue is mainly to clarify the case where "sender address" nor "receiver address" are provided, since those parameters are necessary for lotus to get a good gas estimate.

@qiwu7 - When `/construction/metadata ` is used as "gas fee tracker" (where the `options` field is not present), would be ok to retrieve only `gasPremium` ? (seems this variable is the only candidate to be queried without actually passing a sender address).

**Comment by qiwu7** [comment]
hmm. I think we originally had a discussion that it would useful to just get the gasPrice when the `options` object in the request is empty. Now that these gas estimates relies on the address, then we should always supply the address when making this call.

Also why we need a receiver address? What's that for?

**Comment by qiwu7** [comment]
I also want to report a `bug`? regarding the fee estimation. The response I am getting indicates a higher `GasEstimateGasPremium` than `GasEstimateFeeCap`. According to the [v0.5.0 release note](https://github.com/filecoin-project/lotus/releases/tag/v0.5.0), GasFeeCap should be larger than `GasPremium`.

> A sender will never be charged more than GasFeeCap * GasLimit.
    A miner will typically earn GasPremium * GasLimit as a reward.

request
```
curl --location --request POST '{{node-url}}/construction/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnetnet"
    },
    "options": {
        "idSender": "t1d5l22aypjpzvtjbjsalw3gauwdf2edeqn6h2lui"
    }
}'
```

response
```
{
    "metadata": {
        "chainID": "testnetnet",
        "gasFeeCap": "119",
        "gasLimit": "10000000000",
        "gasPremium": "122201",
        "nonce": 1
    }
}
```

**Comment by jleni** [comment]
@qiwu7 I just opened your report as another issue

**Comment by raynaudoe** [comment]
Moved discussion to #52
