### ISSUE TITLE
Gas estimation - out of spec behavior?

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-proxy#52]
I also want to report a `bug`? regarding the fee estimation. The response I am getting indicates a higher `GasEstimateGasPremium` than `GasEstimateFeeCap`. According to the [v0.5.0 release note](https://github.com/filecoin-project/lotus/releases/tag/v0.5.0), GasFeeCap should be larger than `GasPremium`.

> A sender will never be charged more than GasFeeCap * GasLimit.
    A miner will typically earn GasPremium * GasLimit as a reward.

request
```
curl --location --request POST '{{node-url}}/construction/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnetnet"
    },
    "options": {
        "idSender": "t1d5l22aypjpzvtjbjsalw3gauwdf2edeqn6h2lui"
    }
}'
```

response
```
{
    "metadata": {
        "chainID": "testnetnet",
        "gasFeeCap": "119",
        "gasLimit": "10000000000",
        "gasPremium": "122201",
        "nonce": 1
    }
}
```

_Originally posted by @qiwu7 in https://github.com/Zondax/rosetta-filecoin-proxy/issues/50#issuecomment-692970592_

**Comment by raynaudoe** [comment]
This is already fixed on master branch
