### ISSUE TITLE
/account/balance error

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#58]
```
curl --location --request POST '{{node-url}}/account/balance' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnetnet"
    },
     "account_identifier": {
        "address": "t1jabfbjgax5kbexiwzxjiii6le5yxtu43ui4jcaq",
        "metadata": {}
    }
}'
```

response 
```
{
    "code": 38,
    "message": "could not retrieve actor from address",
    "retriable": false
}
```

This is a address that is not registered on chain I believe. we should return 0 balance for this. Or return a more granular error that we can add handle for

**Comment by raynaudoe** [comment]
If we return something not null along with an error message it will break the consistency of the responses: if there's a irreparable  error the response object will always be null.

> Or return a more granular error that we can add handle for

I can clarify that error adding something like "address not found on chain" or the one you need to handle this case.

**Comment by raynaudoe** [comment]
Error should now be clearer on their origin.
Proxy returns the underlying Lotus error that caused the error in the first place (if corresponds). Added on #62
