### ISSUE TITLE
/construction/metadata/

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#59]
this is returning 500 for me after the upgrade to v.0.7.0

```
curl --location --request POST '{{url}}/construction/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnetnet"
    },
    "options": {
        "idSender": "t1zdqprv6ryul3md3xiqpsczpui7xmqwjztvhirsy"
    }
}'
```

```
{
    "code": 44,
    "message": "unable to estimate gas limit",
    "retriable": false
}
```

**Comment by raynaudoe** [comment]
If you pass the sender address you also need to pass the receiver's.
Lotus needs both to get a good estimate on gas fees.
Check out: https://filecoinproject.slack.com/archives/G015X3KLKB6/p1599255450028700

From rosetta-proxy perspective, there are two ways of getting gas fees:
- _Providing sender & receiver_: most accurate estimates for `gasLimit`, `gasPremium` and `gasFeecap`.
- _Not providing any address_: without that info Lotus can only provide an estimate for `gasPremium`

Maybe a good idea would be to return, in this case, another error code like "cannot estimate gas, receiver address is missing"

**Comment by qiwu7** [comment]
reporting another issue with the `construction/metadata`

```
curl --location --request POST 'http://10.200.70.104:8080/construction/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnetnet"
    },
    "options": {
        "idSender": "t1davxd5spqeb5mts45e2v2xqkhwx2ayvzjqeydvi",
        "idReceiver": "t1hif7sm5jm7qfspiolo5ovmuyarfr2zzgbdr3qzi"
    }
}'
```

```
{
    "code": 44,
    "message": "unable to estimate gas limit",
    "retriable": false
}
```

**Comment by raynaudoe** [comment]
I've replaced our integration test with those addresses and it's working. Maybe the node was syncing and it couldn't estimate gas because of that ?
On the PR #62 I'm adding an extended Error obj with the underlying Lotus's error message. This should help clarify these situations.

**Comment by qiwu7** [comment]
Appreciated! This seems intermittent, which is more annoying. I hope we can always reproduce...

**Comment by qiwu7** [comment]
Another issue with fee estimation is that the `gasLimit` seems to be very low and results in out of gas failure on chain... here is a sample transaction we made using the fee estimated by the `construction/metadata` endpoint. We are getting `SysErrOutOfGas` according to the explorer 

https://filfox.info/en/message/bafy2bzacebrh2lc6fv3cv3atwmulawm44j2ixieikpixk7ihvrptkkeqbzwb4

**Comment by raynaudoe** [comment]
Yes, It happened to me a few times. I've asked FIlecoin about that issue and followed their recommendation of using `GasEstimateMessageGas` though, but seems that in certain cases it falls a little short on `gasLimit`. 

I'll dig in more to check what's happening.

**Comment by raynaudoe** [comment]
I'll close this issue, we'll keep tracking gas estimation issues on #52 since this is all external dep.
