### ISSUE TITLE
Block N -> N+1. Document process

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-proxy#91]
We should clarify, document and if necessary correct this.

> One question on the new release. I remember the messages that is included in Block height N is not executed until height N+1. The previous implementation is returning transactions that are included in block N in the response of a N+1 block request. However the new implementation (https://github.com/Zondax/rosetta-filecoin-proxy/releases/tag/v0.801.2) using trace api is returning the transaction that is included in Block N in the response of a Block N request.
> Would appreciate some clarification on this

Related to https://github.com/Zondax/rosetta-filecoin-proxy/issues/68#issuecomment-704608236

**Comment by raynaudoe** [comment]
According to the last call with Filecoin's team, considering `N` the querying height, trace api (`StateCompute` endpoint) computes all the messages **included** at height `N-1` that were **executed** at height `N`.

A link to an official Lotus documentation would be best, though.

**Comment by qiwu7** [comment]
looks like we are returning executed messages correctly. Let's close

```
$ lotus state search-msg bafy2bzaceasogrhjxosqmdjyp6lcfhiu2eg24twfszhmvrslg7hesc3ozkrmi
message was executed in tipset: [bafy2bzacedcabkf4eoxcusla6eqah45t6nl2xvkxgcg2lyazobibpkaw5r2hu bafy2bzacebkwu2eewwqk2fk5okzkyumhgihlosjblmbgq4rof2tzcrtbu6isy bafy2bzacebvzxcfjlxmeqjtlwvphzzpy2gxto4dedc5bkemubff4rxowhu5ca bafy2bzaced7wtjq3v5e676bu6yny2d652pvh3tyopx66kzmsp766yzqisxgmk bafy2bzaceaujxcsty5qeiclapea2eo6pw2hkb5mog4bcm23tuzt2pydgsx5ki]
Exit Code: 0
Gas Used: 434268
```

https://filfox.info/en/tipset/106233
