### ISSUE TITLE
metadata should return gasLimit as int64

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#95]
Like all the other numeric fields, we should use string for gasLimit. https://github.com/Zondax/rosetta-filecoin-lib/blob/master/construction_api.go#L90

construction/metadata is actually returning gasLimit as string. so we need to be consistent.
```
curl --location --request POST 'http://10.200.200.103:8080/construction/metadata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "ignition"
    },
    "options": {
        "idSender": "t1zdqprv6ryul3md3xiqpsczpui7xmqwjztvhirsy",
        "idReceiver": "f133w2y5kjs7kmnekx327c5uz4tar2ql47ljup4fy"
    }
}'
```

```
{
    "metadata": {
        "chainID": "ignition",
        "gasFeeCap": "339488886",
        "gasLimit": "1943095",
        "gasPremium": "105181",
        "nonce": 33
    }
}
```

**Comment by jleni** [comment]
As discuss, the original message structure in Lotus defines gasLimit as int64

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/types/message.go#L28-L44

For consistency, we will modify the metadata to align with this

**Comment by jleni** [comment]
I am renaming the issue accordingly
